services:
  devs:
    build:
      context: .
    # depends_on:
    #   - db_mongodb
    command: sleep infinity
    tmpfs:
      - /root/.cache:size=70G,exec
  # db_mongodb:
  #   image: mongo:7
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   command: mongod --bind_ip 0.0.0.0      
