services:
  devs:
    build:
      context: .
    depends_on:
      - edupgvector
    command: sleep infinity
    tmpfs:
      - /root/.cache:size=30G,exec
  edupgvector:
    image: ankane/pgvector
    container_name: edupgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=edu
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=edudb
    restart: unless-stopped